### ISSUE TITLE
Worker Dashboard TaskQueue View

### ISSUE THREAD

**Issue by rossmas** [rossmas/OneRouteLocal#5]
Add a view to the worker dashboard page such that it displays all relevant TaskQueues and their respective tasks

- Step 1: Display view area on page

- Step 2: Get TaskQueue data (semi-regularly) and populate the view

**Comment by badri-krishnan** [comment]
Also 2 more things to note

1) Ability to delete the task that worker finishes
2) Change worker state from busy to idle 

If these 2 things don't happen then assignment callback won't happen because worker is still in the "Busy".
